# Selects all distinct GND-IDs from the GND graph

# Variable: <offset> (should be a parameter)
# Variable: <limit> (should be a parameter)

SELECT ?gndid
WHERE {
	{
		SELECT distinct ?gndid
		WHERE { 
		   GRAPH <http://d-nb.info-gnd/> { ?gndid <http://d-nb.info/standards/elementset/gnd#gndIdentifier> ?o }
		}
		ORDER BY ?gndid
	}
}
OFFSET <offset>
LIMIT <limit>